import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext"
import { ShoppingCartProvider } from "@/context/ShoppingCartContext"

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased container mx-auto`}
      >
        <ShoppingCartProvider>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </ShoppingCartProvider>
      </body>
    </html>
  );
}
